# Dockerfile.frontend
FROM python:3.10-slim

WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# Copy requirements and install
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy source code and UI assets
COPY src/ ./src/
# COPY .env.local ./.env.local #to be handled by railway

# Set environment variables
ENV PYTHONPATH=/app/src
ENV API_URL=http://backend:8000
ENV PYTHONUNBUFFERED=1

# Expose Streamlit port
EXPOSE 8501

# Run the App
CMD ["streamlit", "run", "src/streamlit_app/app.py", "--server.port", "8501", "--server.address", "0.0.0.0"]
